name: Test
on: [push]
jobs:
  image:
    name: Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build DevContainer
        uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/customink/dnd-demo-ci
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: echo DONE!
  test-0:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-1:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-2:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-3:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-4:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-5:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-6:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-7:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-8:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-9:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-10:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-11:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-12:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-13:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-14:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-15:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-16:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-17:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-18:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
  test-19:
    runs-on: ubuntu-20.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: |
            docker run -d --name=dind -t -v /var/run/docker.sock:/var/run/docker.sock docker
            docker exec -t dind docker ps
