name: Test
on: [push]
jobs:
  test-0:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-1:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-2:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-3:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-4:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-5:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-6:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-7:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-8:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-9:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-10:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-11:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-12:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-13:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-14:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-15:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-16:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-17:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-18:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  test-19:
    runs-on: ubuntu-latest
    steps:
      - run: sudo curl -s https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh | bash /dev/stdin 1> /dev/null
  