name: Test
on: [push]
jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build DevContainer
        uses: devcontainers/ci@v0.2
        with:
          push: always
          imageName: ghcr.io/customink/dnd-demo-ci
          cacheFrom: ghcr.io/customink/dnd-demo-ci
          runCmd: echo DONE!
  test-0:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-1:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-2:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-3:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-4:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-5:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-6:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-7:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-8:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
  test-9:
    runs-on: ubuntu-18.04
    needs: image
    steps:
      - uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.2
        with:
          push: never
          cacheFrom: ghcr.io/customink/crypteia-ci
          runCmd: cat /tmp/dockerd.log
